### PR TITLE
update README.md to fix unary call example

### PR DESCRIPTION
**Pull request by xh3b4sd**
After 6 years in golang I came back to javascript and maybe missed out on a couple of things. Though while playing around I noticed the README might be a bit misleading. The first echo example makes a unary call and the client method does not create a stream like in the stream example. In my own tests I got only the callback version working. Fixing this in the README. Let me know if there is more to it I did not get right. <3

### CODE REVIEW

**Comment by xh3b4sd** [comment]
For the lack of a better idea, I am just going to ping @stanley-cheung and @fengli79 who are the top contributors. Is anything missing on my part?

**Comment by stanley-cheung** [comment]
@xh3b4sd Sorry for the delay. I will try to get to this shortly.

**Comment by stanley-cheung** [comment]
Hm @xh3b4sd can you please check out the EasyCLA message above to see if you have signed the appropriate CLA? Thanks.

**Comment by xh3b4sd** [comment]
Alright, I signed.

**Review by stanley-cheung — APPROVED** [review]

**Comment by stanley-cheung** [comment]
Thanks for the contribution!

**Pull request merged**
