### PR TITLE
Included support for JSType maps. 

### PR DESCRIPTION
**Pull request by thomasamills**
The generated code was previously setting the type as a repeated message.

### CODE REVIEW

**Comment by jmzwcn** [comment]
great change, come on!

**Comment by hach-que** [comment]
Please merge this, as the TS definition generator is broken and produces definitions that don't match the JS right now.

**Comment by stanley-cheung** [comment]
@thomasamills Can you please update this PR and rebase to the latest master please? Thanks.

**Comment by jmzwcn** [comment]
this PR has been more than two months without any update, please skip it and avoid to blocking others.

**Comment by jmzwcn** [comment]
why close it? it is a necessary feature. 

@shaxbee, could you please add it?

**Comment by stanley-cheung** [comment]
I can try to resurrect this.

**Comment by shaxbee** [comment]
@jmzwcn this was already done as part of #452

**Pull request closed without merging**
