### PR TITLE
Remove unused imports

### LINKED ISSUE #529: Unused Annotations Imports
My .proto file includes imports that are never used by the generated JS client - eg.
`import google/api/annotations.proto`
`import "protoc-gen-swagger/options/annotations.proto"`

I was able to generate the JS client with `protoc-get-grpc-web`, however, the generated code includes those imports even though they are not used by the client:

```
var google_api_annotations_pb = require('../../google/api/annotations_pb.js')
var protoc$gen$swagger_options_annotations_pb = require('../../protoc-gen-swagger/options/annotations_pb.js')
>>> var `google_protobuf_empty_pb` is declared but its value is never read
```

Is there something in place to prevent unused bindings from being included in the generated code?

Similar issue with grpc-gateway code gen:
https://github.com/grpc-ecosystem/grpc-gateway/issues/310

### PR DESCRIPTION
**Pull request by meling**
This checks which fields are actually used before adding the import alias. That is, some imports are only used by other languages, e.g., option imports such as protopatch for Go. Such imports are not used by Javascript or Typescript, and thus should not be imported. Currently, they result in errors like:

```sh
proto/ag/ag_pb.d.ts:4:30 - error TS2307: Cannot find module '../patch/go_pb' or its corresponding type declarations.

4 import * as patch_go_pb from '../patch/go_pb';
```

Fixes #529.

### CODE REVIEW

**Comment by sampajano** [comment]
Thanks so much for the fix! 😃

I wonder if you could provide a minimal example in the PR description on when this issue appears and how this fix addresses it?

Also, i wonder if you could consider adding a test for this change? I believe the following place might be a good fit:
https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/plugin_test.js

Thanks!! :)

**Comment by meling** [comment]
I'll try to fix these issues. Hopefully later this week.

**Comment by meling** [comment]
Seems unlikely that I'll get to this anytime soon; my brief initial attempts at preparing a test case were not successful (cannot recall the problem, but I think it was related to setup / tooling). While this worked on my particular use case, it is a bit of a hack, so perhaps a more robust solution could be implemented. Closing, but feel free to reopen if anyone else wants to pick this up.

**Comment by sampajano** [comment]
Thanks for the effort and explanation @meling! :)

**Pull request closed without merging**
