### PR TITLE
React example

### PR DESCRIPTION
**Pull request by hunnain**
I have created a React Example in which i have implemented gRPC-Web in Reactjs. I have simply created a Todo Application using gRPC-Web

### CODE REVIEW

**Comment by hunnain** [comment]
Please review my code and merge

**Comment by hunnain** [comment]
@stanley-cheung  please review my code run my code and please merge it everyone wants react example thats why i have created React example of grpc-web

**Comment by hunnain** [comment]
@kokoro-team

**Comment by stanley-cheung** [comment]
After reviewing this PR, I am unlikely to merge this in its current form. This PR is mostly just a straight up copy from the existing "helloworld" example, with a slightly modified "todo" theme. As a convention similar to other gRPC repo, we don't encourage checking in generated code. As for the React aspect of things, there are only a few very straight forward .jsx and .css files, that frankly don't add too much value and don't seem to belong to this repo.

Please feel free to host this in your Github repo if you think this will benefit would-be React and gRPC-Web users. But unfortunately I don't believe this PR fits here.

**Comment by hunnain** [comment]
@stanley-cheung i have created an example because React developer not know how to use in React app so thats why i have created this example so stanley can you tell me where am i wrong so i will correct that thing

**Comment by Emixam23** [comment]
Hey @hunnain ,

I definitely agree with you on fact that react dev wouldn't know how to use grpc (also i am a beginner in reactjs). I would love to know if you moved forward on the process to integrating it and making it works?

**Comment by longfellowone** [comment]
For anyone looking for a simple example. I have created a small sample app here using ReactJS client with a Golang web server.

https://github.com/longfellowone/grpcwebtest

**Pull request closed without merging**
