### PR TITLE
Enable ADVANCED_OPTIMIZATIONS in Closure Compiler

### LINKED ISSUE #270: Reduce compiled JS file size
As it stands, our [npm package](https://www.npmjs.com/package/grpc-web) `index.js` is 218KiB (which is being compiled by the closure compiler [here](https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/scripts/build.js)).

With the [Echo example echo.proto](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echo.proto), that has about 7 message types, 1 service, 3 unary methods and 5 streaming methods:
- The [Closure example](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/Makefile#L60) final `compiled.js` compiled by the Closure compiler: 317KiB
 - The [CommonJS example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/commonjs-example) final `dist/main.js` compiled by `webpack`: 415KiB
 - The same CommonJS example compiled by `browserify`: 479KiB
 - The CommonJS example [with `.d.ts` typings](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/ts-example) generated, and then compiled by `webpack`: 499KiB

I tried `babel-minify` and `uglify-js` on some of these JS files and the output are not any particularly smaller.

There should be some other things we can do to further minimize the compiled JS code size.

Reference: #79

### PR DESCRIPTION
**Pull request by jjbubudi**
Fixes #270

Npm package size went from 217.4KB to **23.3KB (uncompressed)** / **9.3KB (gzipped)**

### CODE REVIEW

**Comment by stanley-cheung** [comment]
@jjbubudi Can you please rebase this PR so that we can run the test suite? Thanks

**Comment by jjbubudi** [comment]
@stanley-cheung Rebased. Please proceed.

**Comment by stanley-cheung** [comment]
@jjbubudi There are some test failure. Please take a look. Thanks!

```
ERROR: /tmpfs/src/github/grpc-web/javascript/net/grpc/web/BUILD.bazel:124:1: Compiling 286 JavaScript files to javascript/net/grpc/web/grpcwebclientbase_test_bin.js failed (Exit 1)
javascript/net/grpc/web/abstractclientbase.js:55: ERROR - @export only applies to symbols/properties defined in the global scope.
  this.responseType = responseType;
  ^
  ProTip: "JSC_NON_GLOBAL_ERROR" can be added to the `suppress` attribute of:
  //javascript/net/grpc/web:abstractclientbase

javascript/net/grpc/web/abstractclientbase.js:57: ERROR - @export only applies to symbols/properties defined in the global scope.
  this.requestSerializeFn = requestSerializeFn;
  ^
  ProTip: "JSC_NON_GLOBAL_ERROR" can be added to the `suppress` attribute of:
  //javascript/net/grpc/web:abstractclientbase

javascript/net/grpc/web/abstractclientbase.js:59: ERROR - @export only applies to symbols/properties defined in the global scope.
  this.responseDeserializeFn = responseDeserializeFn;
  ^
  ProTip: "JSC_NON_GLOBAL_ERROR" can be added to the `suppress` attribute of:
  //javascript/net/grpc/web:abstractclientbase

3 error(s), 0 warning(s), 97.3% typed

INFO: Elapsed time: 91.585s, Critical Path: 56.53s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 695 processes: 394 linux-sandbox, 301 worker.
FAILED: Build did NOT complete successfully
```

**Comment by jjbubudi** [comment]
@stanley-cheung Updated and rebased. Now both bazel test and npm test are passing locally.

**Comment by pumano** [comment]
wow, if it will works, amazing work man @jjbubudi !

**Pull request merged**
