### PR TITLE
Avoid double slash in url when client hostname has tailing slash

### PR DESCRIPTION
**Pull request by hanabi1224**
When GRPC client hostname has tailing '/', the final request url contains '//' which cannot be processed properly by some servers,  e.g.  grpc-dotnet-web

### CODE REVIEW

**Comment by stanley-cheung** [comment]
I am so sorry. I keep looking at this and thought, how would this compile? I will have to look up what this `URL` class is and how it will compile, in C++. Only did I suddenly realize - it's _generated_ code. This is a _javascript_ class. *facepalm*.

Thanks for the contribution. But tests failed. I believe there's a missing comma after `toString()`.

Sorry about the delay.

**Comment by hanabi1224** [comment]
Good catch! Fixed, please take another look

**Comment by Fl0pZz** [comment]
@stanley-cheung @hanabi1224  this PR drop support uri like: `https://example.com/api/grpc/v1/...`

See examples:
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by stanley-cheung** [comment]
@Fl0pZz sorry I am a bit unclear on this - do you mean that you are passing the hostname parameter with the 3 dots at the end?

**Comment by Fl0pZz** [comment]
> @Fl0pZz sorry I am a bit unclear on this - do you mean that you are passing the hostname parameter with the 3 dots at the end?

Nope :) 
I mean host name like this:
Hostname: `https://example.com/api/grpc/v1`

And in browser dev tools i see request: `https://example.com/api/grpc/v1/MyProject.listEntities`

**Comment by stanley-cheung** [comment]
@Fl0pZz and what's wrong with the above?

**Comment by Fl0pZz** [comment]
> @Fl0pZz and what's wrong with the above?

From mdn: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

```js
const hostname = 'https://example.com/api/grpc/v1';
const uri = new URL('/MyProject.listEntities', hostname);

console.log(uri.toString()) // -> https://example.com/MyProject.listEntities
```

however i expected `https://example.com/api/grpc/v1/MyProject.listEntities`

**Pull request merged**
